AWSTemplateFormatVersion: 2010-09-09
Description: Custom resource
Parameters:
  NombreRepo:
    Type: String
    Default: TestRepo

Resources:  
  RepoECRPersonalizado:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt FuncionECR.Arn
      RepoECR: !Ref NombreRepo
      
  FuncionECR:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          import cfnresponse

          response_data = {}

          client = boto3.client('ecr')

          def lambda_handler(event, context):
            try:
              repo=event['ResourceProperties']['RepoECR']
              if event['RequestType'] == 'Create':
                response = client.create_repository(
                  repositoryName=repo.lower(),
                  imageScanningConfiguration={
                    'scanOnPush': True
                  },
                  encryptionConfiguration={
                    'encryptionType': 'AES256'
                  }
                )
                response_data['Uri'] = response['repository']['repositoryUri']
                response_data['Nombre'] = response['repository']['repositoryName']
              elif event['RequestType'] == 'Delete':
                client.delete_repository(
                  repositoryName=repo.lower(),
                  force=True
                )
              
              cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)
              
            except Exception as e:
              response_data['Error'] = str(e)
              cfnresponse.send(event, context, cfnresponse.FAILED, response_data)
      Handler: index.lambda_handler
      Runtime: python3.11
      Role: !GetAtt RolLambdaECR.Arn

  RolLambdaECR:
     Type: AWS::IAM::Role
     Properties:
       AssumeRolePolicyDocument:
         Statement:
         - Action:
           - sts:AssumeRole
           Effect: Allow
           Principal:
             Service:
             - lambda.amazonaws.com
         Version: '2012-10-17'
       Path: "/"
       Policies:
       - PolicyDocument:
           Statement:
           - Action:
             - logs:CreateLogGroup
             - logs:CreateLogStream
             - logs:PutLogEvents
             Effect: Allow
             Resource: arn:aws:logs:*:*:*
           Version: '2012-10-17'
         PolicyName: CloudWatch-Lambda
       - PolicyDocument:
           Statement:
           - Action:
             - ecr:CreateRepository
             - ecr:DeleteRepository
             Effect: Allow
             Resource:
             - '*'
           Version: '2012-10-17'
         PolicyName: ECR-Lambda

Outputs:
  RepoURI:
    Description: URI del repositorio
    Value: !GetAtt RepoECRPersonalizado.Uri